site_name: Odin Toolkits
site_description: Odin Toolkits 是开源的，第三方的 Odin Inspector 扩展工具集。探索 Odin Inspector 进阶功能、整合优质资源、优化游戏开发流程。
site_author: Yuumix
site_url: https://www.odintoolkits.cn/
copyright: Copyright &copy; 2025 Yuumix

# Repository
repo_name: Odin Toolkits For Unity
repo_url: https://github.com/yuumixcode/OdinToolkits-For-Unity

# Navigation
nav:
  - README: 
    - README: README.md
  - Info:
    - CHANGELOG: Information/CHANGELOG.md
    - LICENSE: Information/LICENSE.md
    - LOGO-LICENSE: Information/LOGO-LICENSE.md
  # - ROADMAP: Information/ROADMAP.md
  - Manual:
    - Script Doc Generator:
      - 使用指南: Manual/ScriptDocGenerator/ScriptDocGeneratorUsageGuide.md
      - 单元测试: Manual/ScriptDocGenerator/UnitTestSupports.md
    - Modules:
      - Quick Generate SO: Manual/Modules/QuickGenerateSO.md
  - Scripting API:
    - Odin Toolkits:
      - Script Doc Generator:
        - Editor:
          - DocGeneratorSettingSO: ScriptingAPI/OdinToolkits/ScriptDocGenerator/Editor/DocGeneratorSettingSO.md
          - TypeCacheSO: ScriptingAPI/OdinToolkits/ScriptDocGenerator/Editor/TypesCacheSO.md
        - ConstructorData: ScriptingAPI/OdinToolkits/ScriptDocGenerator/ConstructorData.md
        - DefaultAttributeFilter: ScriptingAPI/OdinToolkits/ScriptDocGenerator/DefaultAttributeFilter.md
        - DerivedMemberDataComparer: ScriptingAPI/OdinToolkits/ScriptDocGenerator/DerivedMemberDataComparer.md
        - EventData: ScriptingAPI/OdinToolkits/ScriptDocGenerator/EventData.md
        - FieldData: ScriptingAPI/OdinToolkits/ScriptDocGenerator/FieldData.md
        - IAttributeFilter: ScriptingAPI/OdinToolkits/ScriptDocGenerator/IAttributeFilter.md
        - IAnalysisDataFactory: ScriptingAPI/OdinToolkits/ScriptDocGenerator/IAnalysisDataFactory.md
        - IConstructorData: ScriptingAPI/OdinToolkits/ScriptDocGenerator/IConstructorData.md
        - IEventData: ScriptingAPI/OdinToolkits/ScriptDocGenerator/IEventData.md
        - IFieldData: ScriptingAPI/OdinToolkits/ScriptDocGenerator/IFieldData.md
        - IMethodData: ScriptingAPI/OdinToolkits/ScriptDocGenerator/IMethodData.md
        - IParameterData: ScriptingAPI/OdinToolkits/ScriptDocGenerator/IParameterData.md
        - IPropertyData: ScriptingAPI/OdinToolkits/ScriptDocGenerator/IPropertyData.md
        - ITypeData: ScriptingAPI/OdinToolkits/ScriptDocGenerator/ITypeData.md
        - MethodData: ScriptingAPI/OdinToolkits/ScriptDocGenerator/MethodData.md
        - ParameterData: ScriptingAPI/OdinToolkits/ScriptDocGenerator/ParameterData.md
        - PropertyData: ScriptingAPI/OdinToolkits/ScriptDocGenerator/PropertyData.md
        - TypeAnalyzerStaticExtensions: ScriptingAPI/OdinToolkits/ScriptDocGenerator/TypeAnalyzerStaticExtensions.md
        - TypeAnalyzerUtility: ScriptingAPI/OdinToolkits/ScriptDocGenerator/TypeAnalyzerUtility.md
        - TypeCategory: ScriptingAPI/OdinToolkits/ScriptDocGenerator/TypeCategory.md
        - TypeData: ScriptingAPI/OdinToolkits/ScriptDocGenerator/TypeData.md
        - YuumixDefaultAnalysisDataFactory: ScriptingAPI/OdinToolkits/ScriptDocGenerator/YuumixDefaultAnalysisDataFactory.md
  - Artical:
    - 2025 年 11 月:
      - C# SOLID 原则: Artical/csharp-SOLID.md
      - C# 架构设计: Artical/csharp-architecture-design.md
    - Odin Inspector:
      - Visual Designer 设计: Artical/OdinInspector/visual-designer.md
  - 关于 Odin Inspector 必读: OdinInspector-license.md
 
# Configuration
theme:
  name: material
  favicon: assets/logo-color-noshadow.png
  logo: assets/logo-color-noshadow.png
  custom_dir: overrides
  language: zh
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.follow
    - search.highlight
    - header.autohide
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: lucide/sun
        name: 切换暗黑模式
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: lucide/moon
        name: 切换亮色模式
  font: false
  icon:
    repo: lucide/github
    tag:
      default: lucide/hash
      unittest: lucide/test-tube
extra:
  tags:
    UnitTest: unittest
  social:
    - icon: fontawesome/solid/mail-bulk
      link: mailto:<zeriying@gmail.com>
      name: 邮件
    - icon: fontawesome/brands/github
      link: https://github.com/yuumixcode
      name: yuumix code

# Additional configuration
extra_css:
  - assets/stylesheets/zensical-official-extra.css
  - assets/stylesheets/fonts.css
  - assets/stylesheets/readthedocs.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/javascripts/tablesort.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.caption
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr